name: "AutoThreat CI"
description: "Generate SBOM, scan for vulnerabilities, and produce a report."
inputs:
  path:
    description: "Path to scan"
    required: false
    default: "."
  api_key:
    description: "API key for AutoThreat platform"
    required: true
  fail_on_severity:
    description: "Fail workflow if vulnerabilities at or above this severity are found"
    required: false
    default: "CRITICAL"
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: "3.12.11"
    
    - run: echo "$HOME/.local/bin" >> $GITHUB_PATH
      shell: bash

    - name: Set inputs as environment variables
      shell: bash
      run: |
        export INPUT_PATH="${{ inputs.path }}"
        export INPUT_API_KEY="${{ inputs.api_key }}"
        export INPUT_FAIL_ON_SEVERITY="${{ inputs.fail_on_severity }}"

    - name: Install Python dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install -r $GITHUB_ACTION_PATH/requirements.txt
      shell: bash

    - name: Install syft
      run: |
        curl -sSfL https://get.anchore.io/syft | sh -s -- -b $HOME/.local/bin
      shell: bash

    - name: Install trivy
      run: |
        curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b $HOME/.local/bin v0.66.0
      shell: bash

    - name: Generate SBOM
      run: |
        bash $GITHUB_ACTION_PATH/scripts/generate_sbom.sh "$INPUT_PATH"
      shell: bash

    - name: Scan SBOM
      run: |
        bash $GITHUB_ACTION_PATH/scripts/scan_sbom.sh sbom.json
      shell: bash

    - name: Build Report
      run: |
        python3 $GITHUB_ACTION_PATH/scripts/build_report.py --vulns vulns.json --sbom sbom.json --output report.json --project "${{ github.repository }}"
      shell: bash

    - name: Sync with platform
      run: |
        python3 $GITHUB_ACTION_PATH/scripts/sync_with_platform.py --sbom sbom.json --api-key "$INPUT_API_KEY" --project "${{ github.repository }}"
      shell: bash

    - name: Upload report artifact
      uses: actions/upload-artifact@v4
      with:
        name: report
        path: report.json
